### ISSUE TITLE
feedback on the test

### ISSUE THREAD

**Issue by dmitry-mightydevops** [stas-an/angular-starter#1]
hi @stas-an,

pls see my feedback below.

- build should be in CI pipeline, not in the Dockerfile
- all of nginx configuration should be in the nginx.conf file, not in the Dockerfile
- nginx.conf should allow angular routes with querystring passed

why do we need duplicate steps in push?

```
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/stas-an/angular:latest
```

- why different versions of github actions are used?
- why do we need checkout in push step?
- let's improve speed of build/push steps
- pls beautify all files - Dockerfile, nginx etc.

pls make changes as PR and keep it open (modify ci pipeline "on" to listen for incoming PRs from the feature/* branches as needed)
